---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frigate-cm
  namespace: frigate
data:
  FRIGATE_RTSP_PASSWORD: "password"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frigate-config
  namespace: frigate
data:
  config.yaml: |
    mqtt:
      enabled: True
      host: mosquitto-svc.mosquitto.svc.cluster.local
      port: 1883

    cameras:
      tuin:
        ffmpeg:
          inputs:
            - path: rtsp://rtsp:12345678@192.168.2.61:554/av_stream/ch0
              roles:
                - detect
                - rtmp

        detect:
          enabled: True
          width: 1280
          height: 720
