apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: frigate
  name: frigate-pvc
  namespace: frigate
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn